// <auto-generated />
using Commerce.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Commerce.Api.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    [Migration("20260520120000_PortalUserRoleAssignments")]
    partial class PortalUserRoleAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model captured in CommerceDbContextModelSnapshot after later migrations.
#pragma warning restore 612, 618
        }
    }
}
